name: shopping_assistant_mobile
description: Android Flutter client for the intelligent shopping assistant MVP.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  android_intent_plus: 6.0.0
  camera: ^0.12.0+1
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
